### ISSUE TITLE
Joining a game/session

### ISSUE THREAD

**Issue by hso132** [DivisionBy-Zero/erpa-sweng#10]
The player can register for a game by clicking a button.

- [x] #5 Requires list available games
- [x] #67 Requires Game Viewer
- [ ] #71 Requires join button backend
