### ISSUE TITLE
Implement GCP server

### ISSUE THREAD

**Issue by rykeuse** [DivisionBy-Zero/erpa-sweng#126]
- [ ] #125 filter/sort bacckend (@hso132)
- [ ] #127 authentification tests (@hso132)
- [x] #128 operation business logic (@roosemberth)
- [x] #129 API endpoints (@roosemberth)
